name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v4

      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.x"

      - name: Rodar os testes
        run: python -m unittest discover -s ./tests  -p 'test_*.py'
